export default [
    {
        value:'AC',
        key:'AC',
        order:1,
        color:'colorLightBlue'
    },
    {
        value:'C',
        key:'C',
        order:2,
        color:'colorLightBlue'
    },
    {
        value:'%',
        key:'%',
        order:3,
        color:'colorLightBlue'
    },
    {
        value:'/',
        key:'/',
        order:4,
        color:'colorLightBlue'
    },
    {
        value:'7',
        key:'7',
        order:5,
        color:'colorLightGray'
    },
    {
        value:'8',
        key:'8',
        order:6,
        color:'colorLightGray'
    },
    {
        value:'9',
        key:'9',
        order:7,
        color:'colorLightGray'
    },
    {
        value:'*',
        key:'*',
        order:8,
        color:'colorLightBlue'
    },
    {
        value:'4',
        key:'4',
        order:9,
        color:'colorLightGray'
    },
    {
        value:'5',
        key:'5',
        order:10,
        color:'colorLightGray'
    },
    {
        value:'6',
        key:'6',
        order:11,
        color:'colorLightGray'
    },
    {
        value:'-',
        key:'-',
        order:12,
        color:'colorLightBlue'
    },
    {
        value:'1',
        key:'1',
        order:13,
        color:'colorLightGray'
    },
    {
        value:'2',
        key:'2',
        order:14,
        color:'colorLightGray'
    },
    {
        value:'3',
        key:'3',
        order:15,
        color:'colorLightGray'
    },
    {
        value:'+',
        key:'+',
        order:16,
        color:'colorLightBlue'
    },
    {
        value:'+/-',
        key:'+/-',
        order:17,
        color:'colorLightGray'
    },
    {
        value:'0',
        key:'0',
        order:18,
        color:'colorLightGray'
    },
    {
        value:'.',
        key:'.',
        order:19,
        color:'colorLightGray'
    },
    {
        value:'=',
        key:'=',
        order:20,
        color:'colorLightBlue'
    },
]